version: "3.7"

services:
  database_devaria:
    image: postgres
    container_name: database_devaria
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=devaria
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: devaria
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_devaria
    depends_on:
      - database_devaria
volumes:
  pgdata:
    driver: local
